import { OpenWeatherResponse } from '../types/OpenWeatherTypes'

type options = {
    public?: boolean
}
export const requestMock = async (
    url: string,
    options?: options
): Promise<OpenWeatherResponse> =>
    new Promise((resolve) => {
        setTimeout(() => resolve(buildOneCallMock()), Math.random() * 1000)
    })

export const buildOneCallMock = () =>
    ({
        lat: 48.8534,
        lon: 2.3488,
        timezone: 'Europe/Paris',
        timezone_offset: 7200,
        current: {
            dt: Date.now(),
            sunrise: 1680326943,
            sunset: 1680373189,
            temp: 14.86,
            feels_like: 13.86,
            pressure: 1006,
            humidity: 56,
            dew_point: 6.17,
            uvi: 1.6,
            clouds: 75,
            visibility: 10000,
            wind_speed: 7.72,
            wind_deg: 290,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
        },
        hourly: [
            {
                dt: 1680354000,
                temp: 14.46,
                feels_like: 13.45,
                pressure: 1006,
                humidity: 57,
                dew_point: 6.06,
                uvi: 2.08,
                clouds: 80,
                visibility: 10000,
                wind_speed: 6.22,
                wind_deg: 272,
                wind_gust: 10.16,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                pop: 0.9,
                rain: {
                    '1h': 0.13,
                },
            },
            {
                dt: 1680357600,
                temp: 14.86,
                feels_like: 13.86,
                pressure: 1006,
                humidity: 56,
                dew_point: 6.17,
                uvi: 1.6,
                clouds: 75,
                visibility: 10000,
                wind_speed: 6.38,
                wind_deg: 283,
                wind_gust: 9.8,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.84,
            },
            {
                dt: 1680361200,
                temp: 14.5,
                feels_like: 13.49,
                pressure: 1006,
                humidity: 57,
                dew_point: 6.09,
                uvi: 1.01,
                clouds: 77,
                visibility: 10000,
                wind_speed: 5.96,
                wind_deg: 292,
                wind_gust: 9.77,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.73,
            },
            {
                dt: 1680364800,
                temp: 13.85,
                feels_like: 12.86,
                pressure: 1006,
                humidity: 60,
                dew_point: 6.23,
                uvi: 0.62,
                clouds: 81,
                visibility: 10000,
                wind_speed: 6.22,
                wind_deg: 298,
                wind_gust: 10.44,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.8,
            },
            {
                dt: 1680368400,
                temp: 12.62,
                feels_like: 11.69,
                pressure: 1007,
                humidity: 67,
                dew_point: 6.66,
                uvi: 0.21,
                clouds: 85,
                visibility: 10000,
                wind_speed: 5.58,
                wind_deg: 302,
                wind_gust: 9.9,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                pop: 1,
                rain: {
                    '1h': 0.16,
                },
            },
            {
                dt: 1680372000,
                temp: 11.24,
                feels_like: 10.4,
                pressure: 1008,
                humidity: 76,
                dew_point: 7.17,
                uvi: 0,
                clouds: 89,
                visibility: 10000,
                wind_speed: 4.86,
                wind_deg: 316,
                wind_gust: 9.17,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                pop: 1,
                rain: {
                    '1h': 0.17,
                },
            },
            {
                dt: 1680375600,
                temp: 10.12,
                feels_like: 9.3,
                pressure: 1010,
                humidity: 81,
                dew_point: 6.84,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.09,
                wind_deg: 318,
                wind_gust: 8.73,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10n',
                    },
                ],
                pop: 0.41,
                rain: {
                    '1h': 0.17,
                },
            },
            {
                dt: 1680379200,
                temp: 9.86,
                feels_like: 7.95,
                pressure: 1011,
                humidity: 82,
                dew_point: 6.74,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 3.75,
                wind_deg: 314,
                wind_gust: 8.52,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10n',
                    },
                ],
                pop: 0.5,
                rain: {
                    '1h': 0.14,
                },
            },
            {
                dt: 1680382800,
                temp: 9.39,
                feels_like: 7.26,
                pressure: 1012,
                humidity: 81,
                dew_point: 6.15,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 3.98,
                wind_deg: 310,
                wind_gust: 8.54,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.31,
            },
            {
                dt: 1680386400,
                temp: 9.02,
                feels_like: 6.7,
                pressure: 1012,
                humidity: 78,
                dew_point: 5.22,
                uvi: 0,
                clouds: 84,
                visibility: 10000,
                wind_speed: 4.22,
                wind_deg: 306,
                wind_gust: 8.65,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.33,
            },
            {
                dt: 1680390000,
                temp: 9.06,
                feels_like: 6.64,
                pressure: 1013,
                humidity: 74,
                dew_point: 4.46,
                uvi: 0,
                clouds: 86,
                visibility: 10000,
                wind_speed: 4.45,
                wind_deg: 306,
                wind_gust: 8.8,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.33,
            },
            {
                dt: 1680393600,
                temp: 8.87,
                feels_like: 6.29,
                pressure: 1013,
                humidity: 78,
                dew_point: 5.01,
                uvi: 0,
                clouds: 88,
                visibility: 10000,
                wind_speed: 4.71,
                wind_deg: 301,
                wind_gust: 9.21,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.38,
            },
            {
                dt: 1680397200,
                temp: 8.66,
                feels_like: 5.93,
                pressure: 1013,
                humidity: 82,
                dew_point: 5.61,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.96,
                wind_deg: 305,
                wind_gust: 9.63,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.21,
            },
            {
                dt: 1680400800,
                temp: 8.55,
                feels_like: 5.71,
                pressure: 1014,
                humidity: 84,
                dew_point: 5.71,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.16,
                wind_deg: 311,
                wind_gust: 9.92,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.22,
            },
            {
                dt: 1680404400,
                temp: 8.4,
                feels_like: 5.53,
                pressure: 1014,
                humidity: 85,
                dew_point: 5.86,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.14,
                wind_deg: 316,
                wind_gust: 10.44,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10n',
                    },
                ],
                pop: 0.3,
                rain: {
                    '1h': 0.13,
                },
            },
            {
                dt: 1680408000,
                temp: 8.26,
                feels_like: 5.39,
                pressure: 1015,
                humidity: 87,
                dew_point: 5.98,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.05,
                wind_deg: 322,
                wind_gust: 10.23,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10n',
                    },
                ],
                pop: 0.42,
                rain: {
                    '1h': 0.29,
                },
            },
            {
                dt: 1680411600,
                temp: 8.22,
                feels_like: 5.44,
                pressure: 1015,
                humidity: 87,
                dew_point: 6.01,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.82,
                wind_deg: 330,
                wind_gust: 9.86,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0.38,
            },
            {
                dt: 1680415200,
                temp: 8.13,
                feels_like: 5.29,
                pressure: 1016,
                humidity: 88,
                dew_point: 6.13,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.9,
                wind_deg: 337,
                wind_gust: 9.6,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.38,
            },
            {
                dt: 1680418800,
                temp: 8.08,
                feels_like: 5.21,
                pressure: 1017,
                humidity: 88,
                dew_point: 5.96,
                uvi: 0.08,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.96,
                wind_deg: 348,
                wind_gust: 9.55,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.18,
            },
            {
                dt: 1680422400,
                temp: 8.07,
                feels_like: 5.14,
                pressure: 1018,
                humidity: 86,
                dew_point: 5.61,
                uvi: 0.21,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.09,
                wind_deg: 353,
                wind_gust: 9.91,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.22,
            },
            {
                dt: 1680426000,
                temp: 7.96,
                feels_like: 5.06,
                pressure: 1019,
                humidity: 85,
                dew_point: 5.39,
                uvi: 0.39,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.96,
                wind_deg: 353,
                wind_gust: 9.28,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.08,
            },
            {
                dt: 1680429600,
                temp: 7.95,
                feels_like: 5,
                pressure: 1020,
                humidity: 83,
                dew_point: 5.12,
                uvi: 0.89,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.06,
                wind_deg: 355,
                wind_gust: 9.73,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.06,
            },
            {
                dt: 1680433200,
                temp: 8.62,
                feels_like: 5.6,
                pressure: 1020,
                humidity: 79,
                dew_point: 4.9,
                uvi: 1.1,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.68,
                wind_deg: 2,
                wind_gust: 9.56,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0.04,
            },
            {
                dt: 1680436800,
                temp: 8.47,
                feels_like: 5.36,
                pressure: 1021,
                humidity: 78,
                dew_point: 4.61,
                uvi: 1.17,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.84,
                wind_deg: 7,
                wind_gust: 10.04,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680440400,
                temp: 7.7,
                feels_like: 4.66,
                pressure: 1022,
                humidity: 79,
                dew_point: 4.15,
                uvi: 1.53,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.13,
                wind_deg: 8,
                wind_gust: 10.06,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680444000,
                temp: 7.85,
                feels_like: 4.86,
                pressure: 1022,
                humidity: 78,
                dew_point: 4.09,
                uvi: 1.18,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.1,
                wind_deg: 13,
                wind_gust: 9.89,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680447600,
                temp: 7.78,
                feels_like: 4.69,
                pressure: 1023,
                humidity: 78,
                dew_point: 3.96,
                uvi: 0.74,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.31,
                wind_deg: 11,
                wind_gust: 9.83,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680451200,
                temp: 7.3,
                feels_like: 4.07,
                pressure: 1023,
                humidity: 78,
                dew_point: 3.56,
                uvi: 0.29,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.33,
                wind_deg: 15,
                wind_gust: 10.58,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680454800,
                temp: 7.39,
                feels_like: 4.45,
                pressure: 1024,
                humidity: 79,
                dew_point: 3.7,
                uvi: 0.1,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.72,
                wind_deg: 16,
                wind_gust: 11.32,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680458400,
                temp: 8.11,
                feels_like: 5.16,
                pressure: 1024,
                humidity: 77,
                dew_point: 4.05,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 5.15,
                wind_deg: 22,
                wind_gust: 9.86,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680462000,
                temp: 8,
                feels_like: 5.09,
                pressure: 1025,
                humidity: 77,
                dew_point: 4.05,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.99,
                wind_deg: 27,
                wind_gust: 10.04,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680465600,
                temp: 7.99,
                feels_like: 5.25,
                pressure: 1026,
                humidity: 77,
                dew_point: 4.04,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.59,
                wind_deg: 25,
                wind_gust: 10.01,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680469200,
                temp: 8.08,
                feels_like: 5.5,
                pressure: 1026,
                humidity: 74,
                dew_point: 3.45,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.29,
                wind_deg: 23,
                wind_gust: 9.47,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680472800,
                temp: 7.99,
                feels_like: 5.49,
                pressure: 1026,
                humidity: 70,
                dew_point: 2.73,
                uvi: 0,
                clouds: 100,
                visibility: 10000,
                wind_speed: 4.08,
                wind_deg: 29,
                wind_gust: 9.06,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680476400,
                temp: 7.61,
                feels_like: 5.13,
                pressure: 1027,
                humidity: 70,
                dew_point: 2.36,
                uvi: 0,
                clouds: 99,
                visibility: 10000,
                wind_speed: 3.88,
                wind_deg: 33,
                wind_gust: 8.94,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680480000,
                temp: 6.94,
                feels_like: 4.47,
                pressure: 1027,
                humidity: 72,
                dew_point: 2.07,
                uvi: 0,
                clouds: 92,
                visibility: 10000,
                wind_speed: 3.59,
                wind_deg: 29,
                wind_gust: 8.72,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680483600,
                temp: 6.38,
                feels_like: 3.81,
                pressure: 1027,
                humidity: 72,
                dew_point: 1.52,
                uvi: 0,
                clouds: 52,
                visibility: 10000,
                wind_speed: 3.55,
                wind_deg: 28,
                wind_gust: 8.64,
                weather: [
                    {
                        id: 803,
                        main: 'Clouds',
                        description: 'broken clouds',
                        icon: '04n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680487200,
                temp: 5.48,
                feels_like: 2.7,
                pressure: 1027,
                humidity: 74,
                dew_point: 0.9,
                uvi: 0,
                clouds: 38,
                visibility: 10000,
                wind_speed: 3.57,
                wind_deg: 32,
                wind_gust: 8.9,
                weather: [
                    {
                        id: 802,
                        main: 'Clouds',
                        description: 'scattered clouds',
                        icon: '03n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680490800,
                temp: 4.85,
                feels_like: 2.02,
                pressure: 1027,
                humidity: 74,
                dew_point: 0.45,
                uvi: 0,
                clouds: 27,
                visibility: 10000,
                wind_speed: 3.44,
                wind_deg: 37,
                wind_gust: 9.53,
                weather: [
                    {
                        id: 802,
                        main: 'Clouds',
                        description: 'scattered clouds',
                        icon: '03n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680494400,
                temp: 4.35,
                feels_like: 1.35,
                pressure: 1027,
                humidity: 74,
                dew_point: -0.09,
                uvi: 0,
                clouds: 20,
                visibility: 10000,
                wind_speed: 3.53,
                wind_deg: 43,
                wind_gust: 9.8,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680498000,
                temp: 3.92,
                feels_like: 0.89,
                pressure: 1027,
                humidity: 74,
                dew_point: -0.61,
                uvi: 0,
                clouds: 16,
                visibility: 10000,
                wind_speed: 3.44,
                wind_deg: 44,
                wind_gust: 9.55,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02n',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680501600,
                temp: 3.72,
                feels_like: 0.63,
                pressure: 1028,
                humidity: 74,
                dew_point: -0.8,
                uvi: 0.09,
                clouds: 14,
                visibility: 10000,
                wind_speed: 3.46,
                wind_deg: 44,
                wind_gust: 9.64,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680505200,
                temp: 4.64,
                feels_like: 1.38,
                pressure: 1028,
                humidity: 69,
                dew_point: -0.81,
                uvi: 0.42,
                clouds: 0,
                visibility: 10000,
                wind_speed: 4.07,
                wind_deg: 46,
                wind_gust: 9.15,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680508800,
                temp: 6.09,
                feels_like: 2.87,
                pressure: 1028,
                humidity: 62,
                dew_point: -0.85,
                uvi: 1.08,
                clouds: 0,
                visibility: 10000,
                wind_speed: 4.64,
                wind_deg: 47,
                wind_gust: 8.68,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680512400,
                temp: 7.56,
                feels_like: 4.52,
                pressure: 1028,
                humidity: 54,
                dew_point: -1.43,
                uvi: 2.03,
                clouds: 1,
                visibility: 10000,
                wind_speed: 5.04,
                wind_deg: 50,
                wind_gust: 7.99,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680516000,
                temp: 8.82,
                feels_like: 5.99,
                pressure: 1028,
                humidity: 47,
                dew_point: -1.97,
                uvi: 2.95,
                clouds: 0,
                visibility: 10000,
                wind_speed: 5.33,
                wind_deg: 51,
                wind_gust: 7.76,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680519600,
                temp: 9.99,
                feels_like: 7.44,
                pressure: 1027,
                humidity: 43,
                dew_point: -2.29,
                uvi: 3.66,
                clouds: 1,
                visibility: 10000,
                wind_speed: 5.38,
                wind_deg: 53,
                wind_gust: 7.71,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
            {
                dt: 1680523200,
                temp: 10.89,
                feels_like: 9.05,
                pressure: 1027,
                humidity: 39,
                dew_point: -2.73,
                uvi: 3.88,
                clouds: 1,
                visibility: 10000,
                wind_speed: 5.47,
                wind_deg: 52,
                wind_gust: 7.64,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                pop: 0,
            },
        ],
        daily: [
            {
                dt: 1680346800,
                sunrise: 1680326943,
                sunset: 1680373189,
                moonrise: 1680354480,
                moonset: 1680322440,
                moon_phase: 0.35,
                temp: {
                    day: 13.32,
                    min: 9.39,
                    max: 14.86,
                    night: 9.39,
                    eve: 12.62,
                    morn: 10.62,
                },
                feels_like: {
                    day: 12.3,
                    night: 7.26,
                    eve: 11.69,
                    morn: 9.75,
                },
                pressure: 1006,
                humidity: 61,
                dew_point: 5.97,
                wind_speed: 8.43,
                wind_deg: 244,
                wind_gust: 17.51,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                clouds: 89,
                pop: 1,
                rain: 2.49,
                uvi: 2.49,
            },
            {
                dt: 1680433200,
                sunrise: 1680413217,
                sunset: 1680459679,
                moonrise: 1680445080,
                moonset: 1680410040,
                moon_phase: 0.38,
                temp: {
                    day: 8.62,
                    min: 7.3,
                    max: 9.06,
                    night: 8.08,
                    eve: 7.39,
                    morn: 8.22,
                },
                feels_like: {
                    day: 5.6,
                    night: 5.5,
                    eve: 4.45,
                    morn: 5.44,
                },
                pressure: 1020,
                humidity: 79,
                dew_point: 4.9,
                wind_speed: 5.84,
                wind_deg: 7,
                wind_gust: 11.32,
                weather: [
                    {
                        id: 500,
                        main: 'Rain',
                        description: 'light rain',
                        icon: '10d',
                    },
                ],
                clouds: 100,
                pop: 0.42,
                rain: 0.42,
                uvi: 1.53,
            },
            {
                dt: 1680519600,
                sunrise: 1680499491,
                sunset: 1680546168,
                moonrise: 1680535680,
                moonset: 1680497460,
                moon_phase: 0.41,
                temp: {
                    day: 9.99,
                    min: 3.72,
                    max: 12.09,
                    night: 7.04,
                    eve: 11.14,
                    morn: 3.92,
                },
                feels_like: {
                    day: 7.44,
                    night: 4.12,
                    eve: 9.38,
                    morn: 0.89,
                },
                pressure: 1027,
                humidity: 43,
                dew_point: -2.29,
                wind_speed: 5.58,
                wind_deg: 54,
                wind_gust: 10.5,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                clouds: 1,
                pop: 0,
                uvi: 3.88,
            },
            {
                dt: 1680606000,
                sunrise: 1680585766,
                sunset: 1680632657,
                moonrise: 1680626220,
                moonset: 1680584760,
                moon_phase: 0.44,
                temp: {
                    day: 10.62,
                    min: 2.21,
                    max: 11.88,
                    night: 7.11,
                    eve: 9.98,
                    morn: 2.33,
                },
                feels_like: {
                    day: 8.6,
                    night: 4.42,
                    eve: 7.9,
                    morn: -1.13,
                },
                pressure: 1027,
                humidity: 33,
                dew_point: -5.13,
                wind_speed: 5.28,
                wind_deg: 51,
                wind_gust: 10.61,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02d',
                    },
                ],
                clouds: 24,
                pop: 0,
                uvi: 3.86,
            },
            {
                dt: 1680692400,
                sunrise: 1680672041,
                sunset: 1680719146,
                moonrise: 1680716880,
                moonset: 1680671940,
                moon_phase: 0.47,
                temp: {
                    day: 11,
                    min: 2.84,
                    max: 12.27,
                    night: 7.79,
                    eve: 10.36,
                    morn: 2.84,
                },
                feels_like: {
                    day: 9.02,
                    night: 6.24,
                    eve: 8.6,
                    morn: 0.18,
                },
                pressure: 1026,
                humidity: 33,
                dew_point: -4.81,
                wind_speed: 4.8,
                wind_deg: 58,
                wind_gust: 8.23,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                clouds: 0,
                pop: 0,
                uvi: 3.85,
            },
            {
                dt: 1680778800,
                sunrise: 1680758317,
                sunset: 1680805635,
                moonrise: 1680807660,
                moonset: 1680759180,
                moon_phase: 0.5,
                temp: {
                    day: 12.96,
                    min: 4.38,
                    max: 14.14,
                    night: 9.03,
                    eve: 11.93,
                    morn: 4.38,
                },
                feels_like: {
                    day: 11.15,
                    night: 7.56,
                    eve: 10.35,
                    morn: 2.45,
                },
                pressure: 1025,
                humidity: 32,
                dew_point: -3.47,
                wind_speed: 4.28,
                wind_deg: 45,
                wind_gust: 7.57,
                weather: [
                    {
                        id: 804,
                        main: 'Clouds',
                        description: 'overcast clouds',
                        icon: '04d',
                    },
                ],
                clouds: 91,
                pop: 0,
                uvi: 4,
            },
            {
                dt: 1680865200,
                sunrise: 1680844593,
                sunset: 1680892124,
                moonrise: 1680898560,
                moonset: 1680846480,
                moon_phase: 0.54,
                temp: {
                    day: 13.71,
                    min: 5.1,
                    max: 14.77,
                    night: 9.82,
                    eve: 12.66,
                    morn: 5.1,
                },
                feels_like: {
                    day: 12.08,
                    night: 7.8,
                    eve: 11.23,
                    morn: 3.06,
                },
                pressure: 1019,
                humidity: 36,
                dew_point: -1.21,
                wind_speed: 5.12,
                wind_deg: 46,
                wind_gust: 10.06,
                weather: [
                    {
                        id: 801,
                        main: 'Clouds',
                        description: 'few clouds',
                        icon: '02d',
                    },
                ],
                clouds: 18,
                pop: 0,
                uvi: 4,
            },
            {
                dt: 1680951600,
                sunrise: 1680930870,
                sunset: 1680978613,
                moonrise: 1680989700,
                moonset: 1680933960,
                moon_phase: 0.57,
                temp: {
                    day: 15.08,
                    min: 6.28,
                    max: 16.26,
                    night: 11.29,
                    eve: 14.17,
                    morn: 6.28,
                },
                feels_like: {
                    day: 13.69,
                    night: 10.25,
                    eve: 13.08,
                    morn: 3.88,
                },
                pressure: 1018,
                humidity: 40,
                dew_point: 1.54,
                wind_speed: 5.53,
                wind_deg: 57,
                wind_gust: 10.99,
                weather: [
                    {
                        id: 800,
                        main: 'Clear',
                        description: 'clear sky',
                        icon: '01d',
                    },
                ],
                clouds: 6,
                pop: 0,
                uvi: 4,
            },
        ],
        alerts: [
            {
                sender_name: 'METEO-FRANCE',
                event: 'Moderate thunderstorm warning',
                start: 1680336337,
                end: 1680386400,
                description:
                    'Moderate damages may occur, especially in vulnerable or in exposed areas and to people who carry out weather-related activities.',
                tags: ['Thunderstorm'],
            },
        ],
    } as OpenWeatherResponse)
